apiVersion: v1
kind: Service
metadata:
  name: common-service
  namespace: kessel-run
  labels:
    app: common-service
  annotations:
    kessel-run.af.mil/service: "common-service"
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: common-service
