spring:
  application:
    name: common-service
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/common_service
    username: kessel_user
    password: kessel_pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: common-service
        health-check-path: /actuator/health

server:
  port: 8080
  servlet:
    context-path: /common-service

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

logging:
  level:
    mil.af.kesselrun: DEBUG
    org.springframework.web: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/common-service.log

# Kessel Run specific configuration
kessel-run:
  security:
    enabled: true
    jwt-secret: kessel-run-secret-key
  monitoring:
    enabled: true
    metrics-path: /metrics
