version: '3.8'

services:
  # Generated Microservices
  common-service:
    build: ./common-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SERVER_PORT=8080
    depends_on:
      - postgres
      - consul
    networks:
      - kessel-run-network


  
  # Infrastructure Services
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_MULTIPLE_DATABASES=common_service
      - POSTGRES_USER=kessel_user
      - POSTGRES_PASSWORD=kessel_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    networks:
      - kessel-run-network
  
  consul:
    image: consul:1.12
    command: agent -server -bootstrap -ui -node=server-1 -bind=0.0.0.0 -client=0.0.0.0
    ports:
      - "8500:8500"
    networks:
      - kessel-run-network
  
  kong:
    image: kong:latest
    environment:
      - KONG_DATABASE=off
      - KONG_DECLARATIVE_CONFIG=/kong/declarative/kong.yml
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"
    volumes:
      - ./api-gateway:/kong/declarative
    networks:
      - kessel-run-network

volumes:
  postgres_data:

networks:
  kessel-run-network:
    driver: bridge
